version: "3.8"
services:
  www:
    build: php-apache
    container_name: www_docker_symfony_2
    ports:
      - "8741:80"
    volumes:
      - ./php-apache/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev
networks:
  dev:
volumes:
  db-data:
